/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package card_game.general;
import javax.swing.*;

/**
 *
 * @author samt
 */
public class GameUI extends GameUIAbstract{

    private final String unconfiguredMenu = "this menu has not been configured yet...";
    
    /**
     * Creates new form GameUI
     * @param g The game that we will be playing :P
     */
    public GameUI(Game g) {
        super(g);
        initComponents();
        for(javax.swing.JButton b : game.buttons()){
            jPanel2.add(b);
            b.addActionListener(this);
        }
        putAccounts();
    }
    
    @Override
    public void actionPerformed(java.awt.event.ActionEvent a){
        if(a.getActionCommand().equalsIgnoreCase("exit")){
            dispose();
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deckOpts = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        deckOptsOk = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        outputPane = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        deckOptsMenu = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        temp2 = new javax.swing.JMenuItem();
        accountsMenu = new javax.swing.JMenu();
        addAccount = new javax.swing.JMenuItem();

        deckOpts.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        deckOpts.setTitle("Deck Options");
        deckOpts.setAlwaysOnTop(true);
        deckOpts.setLocation(getLocation());
        deckOpts.setResizable(false);
        deckOpts.setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Number of Decks:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        deckOptsOk.setText("Ok");
        deckOptsOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deckOptsOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deckOptsLayout = new javax.swing.GroupLayout(deckOpts.getContentPane());
        deckOpts.getContentPane().setLayout(deckOptsLayout);
        deckOptsLayout.setHorizontalGroup(
            deckOptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deckOptsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deckOptsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deckOptsOk)
                .addContainerGap())
        );
        deckOptsLayout.setVerticalGroup(
            deckOptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deckOptsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deckOptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(deckOptsOk)
                .addContainerGap())
        );

        deckOpts.pack();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(game.title);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout outputPaneLayout = new javax.swing.GroupLayout(outputPane);
        outputPane.setLayout(outputPaneLayout);
        outputPaneLayout.setHorizontalGroup(
            outputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        outputPaneLayout.setVerticalGroup(
            outputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        file.setText("File");

        deckOptsMenu.setText("Deck");
        deckOptsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deckOptsMenuActionPerformed(evt);
            }
        });
        file.add(deckOptsMenu);

        jMenuBar1.add(file);

        edit.setText("Edit");

        temp2.setText(unconfiguredMenu);
        temp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temp2ActionPerformed(evt);
            }
        });
        edit.add(temp2);

        jMenuBar1.add(edit);

        accountsMenu.setText("Accounts");

        addAccount.setText("Add Account");
        addAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccountActionPerformed(evt);
            }
        });
        accountsMenu.add(addAccount);

        jMenuBar1.add(accountsMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outputPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temp2ActionPerformed

    private void deckOptsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deckOptsMenuActionPerformed
        deckOpts.setVisible(true);
    }//GEN-LAST:event_deckOptsMenuActionPerformed

    private void addAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountActionPerformed
        String n = JOptionPane.showInputDialog("Enter Name");
        var a = new Account(n, game.defaultMon);
        var cb = new AccountCheckBox(a);
        cb.addActionListener(game);
        game.accounts.add(cb);
        cb.setSelected(true);
        accountsMenu.add(cb);
        accountsMenu.validate();
    }//GEN-LAST:event_addAccountActionPerformed

    private void deckOptsOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deckOptsOkActionPerformed
        game.setDecknum((int) jSpinner1.getValue());
        game.debug();
    }//GEN-LAST:event_deckOptsOkActionPerformed

    private void putAccounts(){
        game.accounts.forEach((a) -> {
            accountsMenu.add(a);
        });
    }
    
    @Override
    public void updateOutput(){
        outputPane.validate();
        System.out.println(outputPane.getComponentCount());
    }
    

    

    
    /**
     * Set the Nimbus look and feel
     */
    public static void laf(){
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
    }
    
    public void packCenterShow(){
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu accountsMenu;
    private javax.swing.JMenuItem addAccount;
    private javax.swing.JFrame deckOpts;
    private javax.swing.JMenuItem deckOptsMenu;
    private javax.swing.JButton deckOptsOk;
    private javax.swing.JMenu edit;
    private javax.swing.JMenu file;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    public javax.swing.JPanel outputPane;
    private javax.swing.JMenuItem temp2;
    // End of variables declaration//GEN-END:variables
}


